### ISSUE TITLE
Honeybadger with Serverless?

### ISSUE THREAD

**Issue by hexgnu** [honeybadger-io/honeybadger-lambda-node#2]
Hey guys,

We want to use Honeybadger with our Serverless project there's a couple problems I'm assuming I'll run into.

1. How do I configure the npm module to only run on specific environments? Really I only want to run this when SERVERLESS_STAGE === `prod` for instance.

2. Any way to make the boilerplate of wrapping all functions instead of having to modify all handler.js? I'm thinking since serverless has a plugin infrastructure maybe hooking into that? I know you can modify the F object https://github.com/serverless/serverless/blob/master/lib/Function.js#L27 to call a different handler.

Thoughts? Idk if you have something already cooked up on this front.

**Comment by joshuap** [comment]
@hexgnu Sorry for the late reply -- I didn't have Slack notifications set up for this repo apparently. :) What you want to be using is https://github.com/honeybadger-io/honeybadger-node. For your first question look at the [`developmentEnvironments` config option](https://github.com/honeybadger-io/honeybadger-node#advanced-configuration). Our Lambda handler is also [built in](https://github.com/honeybadger-io/honeybadger-node#aws-lambda) to the library, so you just need to wrap your functions with `Honeybadger.lambdaHandler()` after importing and configuring the honeybadger package.

I am not familiar with Serverless but it looks cool, and if you're using it I'm totally down with supporting it. :) It would be easy if they have something like a middleware stack that we could attach to. I'll create an issue on the honeybadger-node repo for that and you can update it with anything you find. I'll also look into it as soon as I can.

**Comment by hexgnu** [comment]
cool yea I'll get the config updated on our end.

Our serverless projects have quite a few functions so being able to hook into middleware instead would be awesome. I think it's definitely possible since the plugins give you access to which handler is hit which would just have to be switched out for something such as Honeybadger.lambdaHandler over handler.handler.

**Comment by joshuap** [comment]
Sounds good! I'll close this issue here and we can continue the discussion on https://github.com/honeybadger-io/honeybadger-node/issues/8
